singularity:
  diffparc_deps: '/cifs/macdonald/shared/snakemake_containers/diffparc_20230502.sif'

tabular: #this is for parsing the data in diffparc csv files
  extract_ids:
    column_rename:
      subj: subj
    patterns:
      subject: (sub-[a-zA-Z0-9]+)

featsets:
  - templateparc


feature_csv_globs:
  vtasnc_surfFA: '**/tabular/*_label-vtasnc_desc-harvardoxford4_seedspervertex-250_method-mrtrix_surfFA.csv'
  vtasnc_surfMD: '**/tabular/*_label-vtasnc_desc-harvardoxford4_seedspervertex-250_method-mrtrix_surfMD.csv'
  vtasnc_bundleFA: '**/tabular/*_label-vtasnc_desc-harvardoxford4_seedspervertex-250_method-mrtrix_bundleFA.csv'
  vtasnc_bundleMD: '**/tabular/*_label-vtasnc_desc-harvardoxford4_seedspervertex-250_method-mrtrix_bundleMD.csv'
  vtasnc_indepconn: '**/tabular/*_label-vtasnc_desc-harvardoxford4_seedspervertex-250_method-mrtrix_indepconn.csv'
  vtasnc_inout: '**/tabular/*_label-vtasnc_desc-harvardoxford4_seedspervertex-250_method-mrtrix_inout.csv'
  vtasnc_surfarea: '**/tabular/*_label-vtasnc_desc-harvardoxford4_seedspervertex-250_method-mrtrix_surfarea.csv'
  vtasnc_surfarearatio: '**/tabular/*_label-vtasnc_desc-harvardoxford4_seedspervertex-250_method-mrtrix_surfarearatio.csv'
  striatum_surfFA: '**/tabular/*_label-striatum_desc-harvardoxford6_seedspervertex-250_method-mrtrix_surfFA.csv'
  striatum_surfMD: '**/tabular/*_label-striatum_desc-harvardoxford6_seedspervertex-250_method-mrtrix_surfMD.csv'
  striatum_bundleFA: '**/tabular/*_label-striatum_desc-harvardoxford6_seedspervertex-250_method-mrtrix_bundleFA.csv'
  striatum_bundleMD: '**/tabular/*_label-striatum_desc-harvardoxford6_seedspervertex-250_method-mrtrix_bundleMD.csv'
  striatum_indepconn: '**/tabular/*_label-striatum_desc-harvardoxford6_seedspervertex-250_method-mrtrix_indepconn.csv'
  striatum_inout: '**/tabular/*_label-striatum_desc-harvardoxford6_seedspervertex-250_method-mrtrix_inout.csv'
  striatum_surfarea: '**/tabular/*_label-striatum_desc-harvardoxford6_seedspervertex-250_method-mrtrix_surfarea.csv'
  striatum_surfarearatio: '**/tabular/*_label-striatum_desc-harvardoxford6_seedspervertex-250_method-mrtrix_surfarearatio.csv'
  surf_volmni: '**/tabular/*_method-mrtrix_surfvolmni.csv'
  surf_vol: '**/tabular/*_method-mrtrix_surfvol.csv'
  synthseg_cortparc_volmni: '**/tabular/*_method-synthsegcortparc_volmni.csv'
  synthseg_cortparc_vol: '**/tabular/*_method-synthsegcortparc_vol.csv'
  synthseg_cortparc_FA: '**/tabular/*_method-synthsegcortparc_FA.csv'
  synthseg_cortparc_MD: '**/tabular/*_method-synthsegcortparc_MD.csv'

# to evaluate different subsets of features
feature_sets:
  templateparc:
    - vtasnc_surfFA
    - vtasnc_surfMD
    - vtasnc_inout
    - vtasnc_surfarea
    - vtasnc_surfarearatio
    - striatum_surfFA
    - striatum_surfMD
    - striatum_inout
    - striatum_surfarea
    - striatum_surfarearatio
    - surf_volmni
    - synthseg_cortparc_volmni
    - synthseg_cortparc_FA
    - synthseg_cortparc_MD

  all:
    - vtasnc_surfFA
    - vtasnc_surfMD
    - vtasnc_bundleFA
    - vtasnc_bundleMD
    - vtasnc_indepconn
    - vtasnc_inout
    - vtasnc_surfarea
    - vtasnc_surfarearatio
    - striatum_surfFA
    - striatum_surfMD
    - striatum_bundleFA
    - striatum_bundleMD
    - striatum_indepconn
    - striatum_inout
    - striatum_surfarea
    - striatum_surfarearatio
    - surf_volmni
    - synthseg_cortparc_volmni
    - synthseg_cortparc_FA
    - synthseg_cortparc_MD
  subcort_all:
    - vtasnc_surfFA
    - vtasnc_surfMD
    - vtasnc_bundleFA
    - vtasnc_bundleMD
    - vtasnc_indepconn
    - striatum_surfFA
    - striatum_surfMD
    - striatum_bundleFA
    - striatum_bundleMD
    - striatum_indepconn
    - vtasnc_inout
    - vtasnc_surfarea
    - vtasnc_surfarearatio
    - striatum_inout
    - striatum_surfarea
    - striatum_surfarearatio
  subcort_dti:
    - vtasnc_surfFA
    - vtasnc_surfMD
    - vtasnc_bundleFA
    - vtasnc_bundleMD
    - vtasnc_indepconn
    - striatum_surfFA
    - striatum_surfMD
    - striatum_bundleFA
    - striatum_bundleMD
    - striatum_indepconn
  striatum_dti:
    - striatum_surfFA
    - striatum_surfMD
    - striatum_bundleFA
    - striatum_bundleMD
    - striatum_indepconn
  vtasnc_dti:
    - vtasnc_surfFA
    - vtasnc_surfMD
    - vtasnc_bundleFA
    - vtasnc_bundleMD
    - vtasnc_indepconn
  all_dti:
    - vtasnc_surfFA
    - vtasnc_surfMD
    - vtasnc_bundleFA
    - vtasnc_bundleMD
    - vtasnc_indepconn
    - striatum_surfFA
    - striatum_surfMD
    - striatum_bundleFA
    - striatum_bundleMD
    - striatum_indepconn
    - synthseg_cortparc_FA
    - synthseg_cortparc_MD
  synthseg_dti:
    - synthseg_cortparc_FA
    - synthseg_cortparc_MD
  subcort_morph:
    - vtasnc_inout
    - vtasnc_surfarea
    - vtasnc_surfarearatio
    - striatum_inout
    - striatum_surfarea
    - striatum_surfarearatio
  vtasnc_morph:
    - vtasnc_inout
    - vtasnc_surfarea
    - vtasnc_surfarearatio
  striatum_morph:
    - striatum_inout
    - striatum_surfarea
    - striatum_surfarearatio
  synthseg_all:
    - synthseg_cortparc_FA
    - synthseg_cortparc_MD
    - synthseg_cortparc_volmni
  synthseg_morph:
    - synthseg_cortparc_volmni
  all_morph:
    - surf_volmni
    - surf_vol
    - vtasnc_inout
    - vtasnc_surfarea
    - vtasnc_surfarearatio
    - striatum_inout
    - striatum_surfarea
    - striatum_surfarearatio
    - synthseg_cortparc_volmni
    - synthseg_cortparc_vol
  striatum_all:
    - striatum_surfFA
    - striatum_surfMD
    - striatum_bundleFA
    - striatum_bundleMD
    - striatum_indepconn
    - striatum_inout
    - striatum_surfarea
    - striatum_surfarearatio
  vtasnc_all:
    - vtasnc_surfFA
    - vtasnc_surfMD
    - vtasnc_bundleFA
    - vtasnc_bundleMD
    - vtasnc_indepconn
    - vtasnc_inout
    - vtasnc_surfarea
    - vtasnc_surfarearatio


