$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

definitions:
  filterentry:
    type: object
    additionalProperties:
      type: string
  evententry:
    type: object
    properties:
      workflow:
        type: array
        items: 
          type: string
      filter:
        type: string

properties:
  participants_tsv:
    type: string
  in_dwi_prefix: 
    type: string
  

required:
  - in_dwi_prefix

